wip

diff --git a/ci/build-include-what-you-use.yaml b/ci/build-include-what-you-use.yaml
--- a/ci/build-include-what-you-use.yaml
+++ b/ci/build-include-what-you-use.yaml
@@ -1,21 +1,18 @@
 jobs:
 - job: macos_clang_8_debug
-  displayName: 'include-what-you-use: macOS Clang 8 debug'
+  displayName: 'Build include-what-you-use: macOS Clang 8'
 
   pool:
     vmImage: macOS-10.13
 
   variables:
-    # CXXTRACE_SOURCEDIRECTORY
-    cxxtrace.SourceDirectory: $(System.DefaultWorkingDirectory)
-    # CXXTRACE_BUILDDIRECTORY
-    cxxtrace.BuildDirectory: $(System.DefaultWorkingDirectory)/build
+    # @@@ rename variables
     # CXXTRACE_IWYUDIRECTORY
-    cxxtrace.IWYUDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use/usr
+    cxxtrace.IWYUDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use-prefix
     # CXXTRACE_IWYUSOURCEDIRECTORY
     cxxtrace.IWYUSourceDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use
     # CXXTRACE_IWYUBUILDDIRECTORY
-    cxxtrace.IWYUBuildDirectory: $(System.DefaultWorkingDirectory)/include-what-you-use/build
+    cxxtrace.IWYUBuildDirectory: $(System.DefaultWorkingDirectory)/build
   # @@@ dedupe with build-and-test.yaml
     # CXXTRACE_TOOLCHAINDIRECTORY
     cxxtrace.ToolchainDirectory: $(System.DefaultWorkingDirectory)/toolchain
@@ -24,12 +21,15 @@ jobs:
     # CXXTRACE_TOOLCHAINARCHIVENAME
     cxxtrace.ToolchainArchiveName: clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
     cxxtrace.ToolchainPrettyName: Clang 8.0.0
+    # CXXTRACE_IWYUARCHIVENAME
+    cxxtrace.IWYUArchiveName: include-what-you-use-0.12-clang-8-macos.tar.xz
 
   steps:
+  - checkout: none
+
   - script: |
      set -eux
      mkdir -p -- \
-       "${CXXTRACE_BUILDDIRECTORY}" \
        "${CXXTRACE_IWYUBUILDDIRECTORY}" \
        "${CXXTRACE_TOOLCHAINDIRECTORY}"
     displayName: Configure checkout
@@ -57,12 +57,17 @@ jobs:
     timeoutInMinutes: 60
 
   # @@@ make a proper mirror
-  # @@@ download and extract to a safe place, not cwd
   - script: |
      set -eux
+     if [ -e "${CXXTRACE_IWYUSOURCEDIRECTORY}" ]; then
+       printf 'error: %s should not exist\n' "${CXXTRACE_IWYUSOURCEDIRECTORY}" >&2
+       exit 1
+     fi
      curl --output include-what-you-use-0.12.src.tar.gz 'https://include-what-you-use.org/downloads/include-what-you-use-0.12.src.tar.gz'
-     tar xzf include-what-you-use-0.12.src.tar.gz
-     #mv include-what-you-use "${CXXTRACE_IWYUSOURCEDIRECTORY}"
+     tar xvzf include-what-you-use-0.12.src.tar.gz
+     if ! [ include-what-you-use -ef "${CXXTRACE_IWYUSOURCEDIRECTORY}" ]; then
+       mv include-what-you-use "${CXXTRACE_IWYUSOURCEDIRECTORY}"
+     fi
     displayName: Download include-what-you-use
     workingDirectory: $(System.DefaultWorkingDirectory)
     timeoutInMinutes: 60
@@ -94,43 +99,14 @@ jobs:
      set -eux
      cmake --build . -- -j4
      cmake --build . -- install
+     # TODO(strager): Strip LC_RPATH from executables.
     displayName: Build include-what-you-use
     workingDirectory: $(cxxtrace.IWYUBuildDirectory)
 
-  # @@@ dedupe with build-and-test.yaml?
-  - script: |
-     set -eux
-     cxxtrace_toolchain_usr="${CXXTRACE_TOOLCHAINDIRECTORY}/usr"
-     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${cxxtrace_toolchain_usr}/bin:${PATH}"
-     cflags="-D_LIBCPP_DISABLE_AVAILABILITY -Wall -Wextra -pedantic -Wno-c99-extensions"
-     ldflags="-L${cxxtrace_toolchain_usr}/lib ${cxxtrace_toolchain_usr}/lib/libc++.a ${cxxtrace_toolchain_usr}/lib/libc++abi.a ${cxxtrace_toolchain_usr}/lib/libc++experimental.a ${cxxtrace_toolchain_usr}/lib/libc++fs.a"
-     cmake \
-       -G 'Unix Makefiles' \
-       -DBUILD_TESTING=ON \
-       -DCMAKE_BUILD_TYPE=Debug \
-       -DCMAKE_C_COMPILER=clang \
-       -DCMAKE_CXX_COMPILER=clang++ \
-       -DCMAKE_C_FLAGS="${cflags}" \
-       -DCMAKE_CXX_FLAGS="${cflags}" \
-       -DCMAKE_EXE_LINKER_FLAGS="${ldflags}" \
-       -DCMAKE_SHARED_LINKER_FLAGS="${ldflags}" \
-       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-       "${CXXTRACE_SOURCEDIRECTORY}"
-    displayName: Configure cxxtrace
-    workingDirectory: $(cxxtrace.BuildDirectory)
-    timeoutInMinutes: 180
-
-  - script: |
-     set -eux
-     PATH="${CXXTRACE_IWYUDIRECTORY}/bin:${PATH}"
-     cmake --build . -- include-what-you-use
-    displayName: Run include-what-you-use
-    workingDirectory: $(cxxtrace.BuildDirectory)
-
-  - script: |
-     set -eux
-     git diff
-    displayName: Check include-what-you-use results
-    workingDirectory: $(cxxtrace.SourceDirectory)
+  - task: PublishPipelineArtifact@1
+    displayName: Publish artifacts
+    inputs:
+      artifact: $(cxxtrace.IWYUArchiveName)
+      targetPath: $(cxxtrace.IWYUDirectory)
 
 # @@@ Linux plz
